global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "prometheus-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'deeplake-service'
    static_configs:
      - targets: ['deeplake-service:8000']
    metrics_path: '/api/v1/metrics/prometheus'
    scrape_interval: 30s
    scrape_timeout: 10s
    basic_auth:
      username: 'admin'
      password: 'your-admin-password'  # Change this in production

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']