apiVersion: v1
kind: ConfigMap
metadata:
  name: deeplake-config
  namespace: deeplake
  labels:
    app: deeplake-service
data:
  # Deep Lake Configuration
  DEEPLAKE_STORAGE_LOCATION: "/data/vectors"
  
  # HTTP Server Configuration
  HTTP_HOST: "0.0.0.0"
  HTTP_PORT: "8000"
  HTTP_WORKERS: "4"
  
  # gRPC Server Configuration
  GRPC_HOST: "0.0.0.0"
  GRPC_PORT: "50051"
  GRPC_MAX_WORKERS: "10"
  
  # Authentication
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_HOURS: "24"
  
  # Redis Configuration
  REDIS_URL: "redis://redis:6379/0"
  REDIS_TTL_SECONDS: "3600"
  
  # Monitoring
  MONITORING_ENABLE_METRICS: "true"
  MONITORING_METRICS_PORT: "9090"
  MONITORING_LOG_LEVEL: "INFO"
  MONITORING_LOG_FORMAT: "json"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"
  RATE_LIMIT_BURST: "100"
  
  # Performance
  PERFORMANCE_MAX_VECTOR_BATCH_SIZE: "1000"
  PERFORMANCE_DEFAULT_SEARCH_TIMEOUT: "30"
  PERFORMANCE_MAX_CONCURRENT_SEARCHES: "50"
  
  # Development
  DEV_DEBUG: "false"
  DEV_RELOAD: "false"