apiVersion: v1
kind: Secret
metadata:
  name: deeplake-secrets
  namespace: deeplake
  labels:
    app: deeplake-service
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret" | base64
  JWT_SECRET_KEY: ""  # REQUIRED: Add your JWT secret key here (base64 encoded)
  DEEPLAKE_TOKEN: ""  # Add your Deep Lake token here (base64 encoded)
  DEEPLAKE_ORG_ID: ""  # Add your Deep Lake org ID here (base64 encoded)