apiVersion: v1
kind: Secret
metadata:
  name: deeplake-secrets
  namespace: deeplake
  labels:
    app: deeplake-service
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your-secret" | base64
  JWT_SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # your-secret-key-change-in-production
  DEEPLAKE_TOKEN: ""  # Add your Deep Lake token here (base64 encoded)
  DEEPLAKE_ORG_ID: ""  # Add your Deep Lake org ID here (base64 encoded)